# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/2.8.12.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/2.8.12.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/local/Cellar/cmake/2.8.12.2/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/vincent.cogne/Github/LittleWorld

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/vincent.cogne/Github/LittleWorld

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/2.8.12.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/2.8.12.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/vincent.cogne/Github/LittleWorld/CMakeFiles /Users/vincent.cogne/Github/LittleWorld/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/vincent.cogne/Github/LittleWorld/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named littleWorld

# Build rule for target.
littleWorld: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 littleWorld
.PHONY : littleWorld

# fast build rule for target.
littleWorld/fast:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/build
.PHONY : littleWorld/fast

src/ai/Pathfinder.o: src/ai/Pathfinder.cpp.o
.PHONY : src/ai/Pathfinder.o

# target to build an object file
src/ai/Pathfinder.cpp.o:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/ai/Pathfinder.cpp.o
.PHONY : src/ai/Pathfinder.cpp.o

src/ai/Pathfinder.i: src/ai/Pathfinder.cpp.i
.PHONY : src/ai/Pathfinder.i

# target to preprocess a source file
src/ai/Pathfinder.cpp.i:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/ai/Pathfinder.cpp.i
.PHONY : src/ai/Pathfinder.cpp.i

src/ai/Pathfinder.s: src/ai/Pathfinder.cpp.s
.PHONY : src/ai/Pathfinder.s

# target to generate assembly for a file
src/ai/Pathfinder.cpp.s:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/ai/Pathfinder.cpp.s
.PHONY : src/ai/Pathfinder.cpp.s

src/game/Game.o: src/game/Game.cpp.o
.PHONY : src/game/Game.o

# target to build an object file
src/game/Game.cpp.o:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/game/Game.cpp.o
.PHONY : src/game/Game.cpp.o

src/game/Game.i: src/game/Game.cpp.i
.PHONY : src/game/Game.i

# target to preprocess a source file
src/game/Game.cpp.i:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/game/Game.cpp.i
.PHONY : src/game/Game.cpp.i

src/game/Game.s: src/game/Game.cpp.s
.PHONY : src/game/Game.s

# target to generate assembly for a file
src/game/Game.cpp.s:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/game/Game.cpp.s
.PHONY : src/game/Game.cpp.s

src/graphics/Object.o: src/graphics/Object.cpp.o
.PHONY : src/graphics/Object.o

# target to build an object file
src/graphics/Object.cpp.o:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/graphics/Object.cpp.o
.PHONY : src/graphics/Object.cpp.o

src/graphics/Object.i: src/graphics/Object.cpp.i
.PHONY : src/graphics/Object.i

# target to preprocess a source file
src/graphics/Object.cpp.i:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/graphics/Object.cpp.i
.PHONY : src/graphics/Object.cpp.i

src/graphics/Object.s: src/graphics/Object.cpp.s
.PHONY : src/graphics/Object.s

# target to generate assembly for a file
src/graphics/Object.cpp.s:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/graphics/Object.cpp.s
.PHONY : src/graphics/Object.cpp.s

src/graphics/VBO.o: src/graphics/VBO.cpp.o
.PHONY : src/graphics/VBO.o

# target to build an object file
src/graphics/VBO.cpp.o:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/graphics/VBO.cpp.o
.PHONY : src/graphics/VBO.cpp.o

src/graphics/VBO.i: src/graphics/VBO.cpp.i
.PHONY : src/graphics/VBO.i

# target to preprocess a source file
src/graphics/VBO.cpp.i:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/graphics/VBO.cpp.i
.PHONY : src/graphics/VBO.cpp.i

src/graphics/VBO.s: src/graphics/VBO.cpp.s
.PHONY : src/graphics/VBO.s

# target to generate assembly for a file
src/graphics/VBO.cpp.s:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/graphics/VBO.cpp.s
.PHONY : src/graphics/VBO.cpp.s

src/graphics/object/Light.o: src/graphics/object/Light.cpp.o
.PHONY : src/graphics/object/Light.o

# target to build an object file
src/graphics/object/Light.cpp.o:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/graphics/object/Light.cpp.o
.PHONY : src/graphics/object/Light.cpp.o

src/graphics/object/Light.i: src/graphics/object/Light.cpp.i
.PHONY : src/graphics/object/Light.i

# target to preprocess a source file
src/graphics/object/Light.cpp.i:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/graphics/object/Light.cpp.i
.PHONY : src/graphics/object/Light.cpp.i

src/graphics/object/Light.s: src/graphics/object/Light.cpp.s
.PHONY : src/graphics/object/Light.s

# target to generate assembly for a file
src/graphics/object/Light.cpp.s:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/graphics/object/Light.cpp.s
.PHONY : src/graphics/object/Light.cpp.s

src/graphics/object/Mesh.o: src/graphics/object/Mesh.cpp.o
.PHONY : src/graphics/object/Mesh.o

# target to build an object file
src/graphics/object/Mesh.cpp.o:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/graphics/object/Mesh.cpp.o
.PHONY : src/graphics/object/Mesh.cpp.o

src/graphics/object/Mesh.i: src/graphics/object/Mesh.cpp.i
.PHONY : src/graphics/object/Mesh.i

# target to preprocess a source file
src/graphics/object/Mesh.cpp.i:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/graphics/object/Mesh.cpp.i
.PHONY : src/graphics/object/Mesh.cpp.i

src/graphics/object/Mesh.s: src/graphics/object/Mesh.cpp.s
.PHONY : src/graphics/object/Mesh.s

# target to generate assembly for a file
src/graphics/object/Mesh.cpp.s:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/graphics/object/Mesh.cpp.s
.PHONY : src/graphics/object/Mesh.cpp.s

src/graphics/object/Sprite.o: src/graphics/object/Sprite.cpp.o
.PHONY : src/graphics/object/Sprite.o

# target to build an object file
src/graphics/object/Sprite.cpp.o:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/graphics/object/Sprite.cpp.o
.PHONY : src/graphics/object/Sprite.cpp.o

src/graphics/object/Sprite.i: src/graphics/object/Sprite.cpp.i
.PHONY : src/graphics/object/Sprite.i

# target to preprocess a source file
src/graphics/object/Sprite.cpp.i:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/graphics/object/Sprite.cpp.i
.PHONY : src/graphics/object/Sprite.cpp.i

src/graphics/object/Sprite.s: src/graphics/object/Sprite.cpp.s
.PHONY : src/graphics/object/Sprite.s

# target to generate assembly for a file
src/graphics/object/Sprite.cpp.s:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/graphics/object/Sprite.cpp.s
.PHONY : src/graphics/object/Sprite.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/math/Frustum.o: src/math/Frustum.cpp.o
.PHONY : src/math/Frustum.o

# target to build an object file
src/math/Frustum.cpp.o:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/math/Frustum.cpp.o
.PHONY : src/math/Frustum.cpp.o

src/math/Frustum.i: src/math/Frustum.cpp.i
.PHONY : src/math/Frustum.i

# target to preprocess a source file
src/math/Frustum.cpp.i:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/math/Frustum.cpp.i
.PHONY : src/math/Frustum.cpp.i

src/math/Frustum.s: src/math/Frustum.cpp.s
.PHONY : src/math/Frustum.s

# target to generate assembly for a file
src/math/Frustum.cpp.s:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/math/Frustum.cpp.s
.PHONY : src/math/Frustum.cpp.s

src/math/Matrix4x4f.o: src/math/Matrix4x4f.cpp.o
.PHONY : src/math/Matrix4x4f.o

# target to build an object file
src/math/Matrix4x4f.cpp.o:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/math/Matrix4x4f.cpp.o
.PHONY : src/math/Matrix4x4f.cpp.o

src/math/Matrix4x4f.i: src/math/Matrix4x4f.cpp.i
.PHONY : src/math/Matrix4x4f.i

# target to preprocess a source file
src/math/Matrix4x4f.cpp.i:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/math/Matrix4x4f.cpp.i
.PHONY : src/math/Matrix4x4f.cpp.i

src/math/Matrix4x4f.s: src/math/Matrix4x4f.cpp.s
.PHONY : src/math/Matrix4x4f.s

# target to generate assembly for a file
src/math/Matrix4x4f.cpp.s:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/math/Matrix4x4f.cpp.s
.PHONY : src/math/Matrix4x4f.cpp.s

src/math/Vector3.o: src/math/Vector3.cpp.o
.PHONY : src/math/Vector3.o

# target to build an object file
src/math/Vector3.cpp.o:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/math/Vector3.cpp.o
.PHONY : src/math/Vector3.cpp.o

src/math/Vector3.i: src/math/Vector3.cpp.i
.PHONY : src/math/Vector3.i

# target to preprocess a source file
src/math/Vector3.cpp.i:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/math/Vector3.cpp.i
.PHONY : src/math/Vector3.cpp.i

src/math/Vector3.s: src/math/Vector3.cpp.s
.PHONY : src/math/Vector3.s

# target to generate assembly for a file
src/math/Vector3.cpp.s:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/math/Vector3.cpp.s
.PHONY : src/math/Vector3.cpp.s

src/math/Vector3Util.o: src/math/Vector3Util.cpp.o
.PHONY : src/math/Vector3Util.o

# target to build an object file
src/math/Vector3Util.cpp.o:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/math/Vector3Util.cpp.o
.PHONY : src/math/Vector3Util.cpp.o

src/math/Vector3Util.i: src/math/Vector3Util.cpp.i
.PHONY : src/math/Vector3Util.i

# target to preprocess a source file
src/math/Vector3Util.cpp.i:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/math/Vector3Util.cpp.i
.PHONY : src/math/Vector3Util.cpp.i

src/math/Vector3Util.s: src/math/Vector3Util.cpp.s
.PHONY : src/math/Vector3Util.s

# target to generate assembly for a file
src/math/Vector3Util.cpp.s:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/math/Vector3Util.cpp.s
.PHONY : src/math/Vector3Util.cpp.s

src/resources/Notifications.o: src/resources/Notifications.cpp.o
.PHONY : src/resources/Notifications.o

# target to build an object file
src/resources/Notifications.cpp.o:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/resources/Notifications.cpp.o
.PHONY : src/resources/Notifications.cpp.o

src/resources/Notifications.i: src/resources/Notifications.cpp.i
.PHONY : src/resources/Notifications.i

# target to preprocess a source file
src/resources/Notifications.cpp.i:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/resources/Notifications.cpp.i
.PHONY : src/resources/Notifications.cpp.i

src/resources/Notifications.s: src/resources/Notifications.cpp.s
.PHONY : src/resources/Notifications.s

# target to generate assembly for a file
src/resources/Notifications.cpp.s:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/resources/Notifications.cpp.s
.PHONY : src/resources/Notifications.cpp.s

src/scene/Camera.o: src/scene/Camera.cpp.o
.PHONY : src/scene/Camera.o

# target to build an object file
src/scene/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/scene/Camera.cpp.o
.PHONY : src/scene/Camera.cpp.o

src/scene/Camera.i: src/scene/Camera.cpp.i
.PHONY : src/scene/Camera.i

# target to preprocess a source file
src/scene/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/scene/Camera.cpp.i
.PHONY : src/scene/Camera.cpp.i

src/scene/Camera.s: src/scene/Camera.cpp.s
.PHONY : src/scene/Camera.s

# target to generate assembly for a file
src/scene/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/scene/Camera.cpp.s
.PHONY : src/scene/Camera.cpp.s

src/scene/Entity.o: src/scene/Entity.cpp.o
.PHONY : src/scene/Entity.o

# target to build an object file
src/scene/Entity.cpp.o:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/scene/Entity.cpp.o
.PHONY : src/scene/Entity.cpp.o

src/scene/Entity.i: src/scene/Entity.cpp.i
.PHONY : src/scene/Entity.i

# target to preprocess a source file
src/scene/Entity.cpp.i:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/scene/Entity.cpp.i
.PHONY : src/scene/Entity.cpp.i

src/scene/Entity.s: src/scene/Entity.cpp.s
.PHONY : src/scene/Entity.s

# target to generate assembly for a file
src/scene/Entity.cpp.s:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/scene/Entity.cpp.s
.PHONY : src/scene/Entity.cpp.s

src/scene/World.o: src/scene/World.cpp.o
.PHONY : src/scene/World.o

# target to build an object file
src/scene/World.cpp.o:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/scene/World.cpp.o
.PHONY : src/scene/World.cpp.o

src/scene/World.i: src/scene/World.cpp.i
.PHONY : src/scene/World.i

# target to preprocess a source file
src/scene/World.cpp.i:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/scene/World.cpp.i
.PHONY : src/scene/World.cpp.i

src/scene/World.s: src/scene/World.cpp.s
.PHONY : src/scene/World.s

# target to generate assembly for a file
src/scene/World.cpp.s:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/scene/World.cpp.s
.PHONY : src/scene/World.cpp.s

src/scene/entity/Dynamic.o: src/scene/entity/Dynamic.cpp.o
.PHONY : src/scene/entity/Dynamic.o

# target to build an object file
src/scene/entity/Dynamic.cpp.o:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/scene/entity/Dynamic.cpp.o
.PHONY : src/scene/entity/Dynamic.cpp.o

src/scene/entity/Dynamic.i: src/scene/entity/Dynamic.cpp.i
.PHONY : src/scene/entity/Dynamic.i

# target to preprocess a source file
src/scene/entity/Dynamic.cpp.i:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/scene/entity/Dynamic.cpp.i
.PHONY : src/scene/entity/Dynamic.cpp.i

src/scene/entity/Dynamic.s: src/scene/entity/Dynamic.cpp.s
.PHONY : src/scene/entity/Dynamic.s

# target to generate assembly for a file
src/scene/entity/Dynamic.cpp.s:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/scene/entity/Dynamic.cpp.s
.PHONY : src/scene/entity/Dynamic.cpp.s

src/scene/entity/Static.o: src/scene/entity/Static.cpp.o
.PHONY : src/scene/entity/Static.o

# target to build an object file
src/scene/entity/Static.cpp.o:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/scene/entity/Static.cpp.o
.PHONY : src/scene/entity/Static.cpp.o

src/scene/entity/Static.i: src/scene/entity/Static.cpp.i
.PHONY : src/scene/entity/Static.i

# target to preprocess a source file
src/scene/entity/Static.cpp.i:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/scene/entity/Static.cpp.i
.PHONY : src/scene/entity/Static.cpp.i

src/scene/entity/Static.s: src/scene/entity/Static.cpp.s
.PHONY : src/scene/entity/Static.s

# target to generate assembly for a file
src/scene/entity/Static.cpp.s:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/scene/entity/Static.cpp.s
.PHONY : src/scene/entity/Static.cpp.s

src/scene/entity/dynamic/Enemy.o: src/scene/entity/dynamic/Enemy.cpp.o
.PHONY : src/scene/entity/dynamic/Enemy.o

# target to build an object file
src/scene/entity/dynamic/Enemy.cpp.o:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/scene/entity/dynamic/Enemy.cpp.o
.PHONY : src/scene/entity/dynamic/Enemy.cpp.o

src/scene/entity/dynamic/Enemy.i: src/scene/entity/dynamic/Enemy.cpp.i
.PHONY : src/scene/entity/dynamic/Enemy.i

# target to preprocess a source file
src/scene/entity/dynamic/Enemy.cpp.i:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/scene/entity/dynamic/Enemy.cpp.i
.PHONY : src/scene/entity/dynamic/Enemy.cpp.i

src/scene/entity/dynamic/Enemy.s: src/scene/entity/dynamic/Enemy.cpp.s
.PHONY : src/scene/entity/dynamic/Enemy.s

# target to generate assembly for a file
src/scene/entity/dynamic/Enemy.cpp.s:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/scene/entity/dynamic/Enemy.cpp.s
.PHONY : src/scene/entity/dynamic/Enemy.cpp.s

src/scene/entity/dynamic/Player.o: src/scene/entity/dynamic/Player.cpp.o
.PHONY : src/scene/entity/dynamic/Player.o

# target to build an object file
src/scene/entity/dynamic/Player.cpp.o:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/scene/entity/dynamic/Player.cpp.o
.PHONY : src/scene/entity/dynamic/Player.cpp.o

src/scene/entity/dynamic/Player.i: src/scene/entity/dynamic/Player.cpp.i
.PHONY : src/scene/entity/dynamic/Player.i

# target to preprocess a source file
src/scene/entity/dynamic/Player.cpp.i:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/scene/entity/dynamic/Player.cpp.i
.PHONY : src/scene/entity/dynamic/Player.cpp.i

src/scene/entity/dynamic/Player.s: src/scene/entity/dynamic/Player.cpp.s
.PHONY : src/scene/entity/dynamic/Player.s

# target to generate assembly for a file
src/scene/entity/dynamic/Player.cpp.s:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/scene/entity/dynamic/Player.cpp.s
.PHONY : src/scene/entity/dynamic/Player.cpp.s

src/scene/entity/static/Decor.o: src/scene/entity/static/Decor.cpp.o
.PHONY : src/scene/entity/static/Decor.o

# target to build an object file
src/scene/entity/static/Decor.cpp.o:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/scene/entity/static/Decor.cpp.o
.PHONY : src/scene/entity/static/Decor.cpp.o

src/scene/entity/static/Decor.i: src/scene/entity/static/Decor.cpp.i
.PHONY : src/scene/entity/static/Decor.i

# target to preprocess a source file
src/scene/entity/static/Decor.cpp.i:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/scene/entity/static/Decor.cpp.i
.PHONY : src/scene/entity/static/Decor.cpp.i

src/scene/entity/static/Decor.s: src/scene/entity/static/Decor.cpp.s
.PHONY : src/scene/entity/static/Decor.s

# target to generate assembly for a file
src/scene/entity/static/Decor.cpp.s:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/scene/entity/static/Decor.cpp.s
.PHONY : src/scene/entity/static/Decor.cpp.s

src/scene/entity/static/Emitter.o: src/scene/entity/static/Emitter.cpp.o
.PHONY : src/scene/entity/static/Emitter.o

# target to build an object file
src/scene/entity/static/Emitter.cpp.o:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/scene/entity/static/Emitter.cpp.o
.PHONY : src/scene/entity/static/Emitter.cpp.o

src/scene/entity/static/Emitter.i: src/scene/entity/static/Emitter.cpp.i
.PHONY : src/scene/entity/static/Emitter.i

# target to preprocess a source file
src/scene/entity/static/Emitter.cpp.i:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/scene/entity/static/Emitter.cpp.i
.PHONY : src/scene/entity/static/Emitter.cpp.i

src/scene/entity/static/Emitter.s: src/scene/entity/static/Emitter.cpp.s
.PHONY : src/scene/entity/static/Emitter.s

# target to generate assembly for a file
src/scene/entity/static/Emitter.cpp.s:
	$(MAKE) -f CMakeFiles/littleWorld.dir/build.make CMakeFiles/littleWorld.dir/src/scene/entity/static/Emitter.cpp.s
.PHONY : src/scene/entity/static/Emitter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... littleWorld"
	@echo "... rebuild_cache"
	@echo "... src/ai/Pathfinder.o"
	@echo "... src/ai/Pathfinder.i"
	@echo "... src/ai/Pathfinder.s"
	@echo "... src/game/Game.o"
	@echo "... src/game/Game.i"
	@echo "... src/game/Game.s"
	@echo "... src/graphics/Object.o"
	@echo "... src/graphics/Object.i"
	@echo "... src/graphics/Object.s"
	@echo "... src/graphics/VBO.o"
	@echo "... src/graphics/VBO.i"
	@echo "... src/graphics/VBO.s"
	@echo "... src/graphics/object/Light.o"
	@echo "... src/graphics/object/Light.i"
	@echo "... src/graphics/object/Light.s"
	@echo "... src/graphics/object/Mesh.o"
	@echo "... src/graphics/object/Mesh.i"
	@echo "... src/graphics/object/Mesh.s"
	@echo "... src/graphics/object/Sprite.o"
	@echo "... src/graphics/object/Sprite.i"
	@echo "... src/graphics/object/Sprite.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/math/Frustum.o"
	@echo "... src/math/Frustum.i"
	@echo "... src/math/Frustum.s"
	@echo "... src/math/Matrix4x4f.o"
	@echo "... src/math/Matrix4x4f.i"
	@echo "... src/math/Matrix4x4f.s"
	@echo "... src/math/Vector3.o"
	@echo "... src/math/Vector3.i"
	@echo "... src/math/Vector3.s"
	@echo "... src/math/Vector3Util.o"
	@echo "... src/math/Vector3Util.i"
	@echo "... src/math/Vector3Util.s"
	@echo "... src/resources/Notifications.o"
	@echo "... src/resources/Notifications.i"
	@echo "... src/resources/Notifications.s"
	@echo "... src/scene/Camera.o"
	@echo "... src/scene/Camera.i"
	@echo "... src/scene/Camera.s"
	@echo "... src/scene/Entity.o"
	@echo "... src/scene/Entity.i"
	@echo "... src/scene/Entity.s"
	@echo "... src/scene/World.o"
	@echo "... src/scene/World.i"
	@echo "... src/scene/World.s"
	@echo "... src/scene/entity/Dynamic.o"
	@echo "... src/scene/entity/Dynamic.i"
	@echo "... src/scene/entity/Dynamic.s"
	@echo "... src/scene/entity/Static.o"
	@echo "... src/scene/entity/Static.i"
	@echo "... src/scene/entity/Static.s"
	@echo "... src/scene/entity/dynamic/Enemy.o"
	@echo "... src/scene/entity/dynamic/Enemy.i"
	@echo "... src/scene/entity/dynamic/Enemy.s"
	@echo "... src/scene/entity/dynamic/Player.o"
	@echo "... src/scene/entity/dynamic/Player.i"
	@echo "... src/scene/entity/dynamic/Player.s"
	@echo "... src/scene/entity/static/Decor.o"
	@echo "... src/scene/entity/static/Decor.i"
	@echo "... src/scene/entity/static/Decor.s"
	@echo "... src/scene/entity/static/Emitter.o"
	@echo "... src/scene/entity/static/Emitter.i"
	@echo "... src/scene/entity/static/Emitter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

